services:
  django:
    build:
      context: .
    container_name: django-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    working_dir: /app
    environment:
      - DEBUG=1
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    networks:
      - my_django_network

  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - my_django_network

  celery-worker:
    build:
      context: .
    container_name: celery-worker
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: sh -c "wait-for-it redis:6379 -- celery -A vote_cast worker --loglevel=info"
    env_file:
      - .env
    networks:
      - my_django_network

networks:
  my_django_network:
    driver: bridge

volumes:
  redis-data:
